package com.eduai.backend_java.models;

import jakarta.persistence.*;
import lombok.Data;

@Data
@Entity
@Table(name = "placement_results")
public class StudentResult {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // --- Data Submitted by React ---
    private String studentId;
    private String name;
    private Double attendance;
    private Double assessmentScore;

    // --- Data Generated by Python AI ---
    private Double readinessScore;
    private String prediction;
    
    @Column(columnDefinition = "TEXT")
    private String shapExplanation;
}